/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ALardanRouteImport } from './routes/a-lardan'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as ColecoesRouteImport } from './routes/colecoes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as SejaLardanRouteImport } from './routes/seja-lardan'
import { Route as SemijoiasRouteImport } from './routes/semijoias'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as SemijoiasAneisRouteImport } from './routes/semijoias.aneis'
import { Route as SemijoiasColaresRouteImport } from './routes/semijoias.colares'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin/estoque'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin/financeiro'
import { Route as AuthenticatedAdminImportacaoRouteImport } from './routes/_authenticated/admin/importacao'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin/integracoes'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminSiteRouteImport } from './routes/_authenticated/admin/site'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminCadastrosIndexRouteImport } from './routes/_authenticated/admin/cadastros/index'
import { Route as AuthenticatedAdminCadastrosCategoriasRouteImport } from './routes/_authenticated/admin/cadastros/categorias'
import { Route as AuthenticatedAdminCadastrosColecoesRouteImport } from './routes/_authenticated/admin/cadastros/colecoes'
import { Route as AuthenticatedAdminCadastrosEntidadesRouteImport } from './routes/_authenticated/admin/cadastros/entidades'
import { Route as AuthenticatedAdminCadastrosFornecedoresRouteImport } from './routes/_authenticated/admin/cadastros/fornecedores'
import { Route as AuthenticatedAdminCadastrosLocaisRouteImport } from './routes/_authenticated/admin/cadastros/locais'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ALardanRoute = ALardanRouteImport.update({
  id: '/a-lardan',
  path: '/a-lardan',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesRoute = ColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaLardanRoute = SejaLardanRouteImport.update({
  id: '/seja-lardan',
  path: '/seja-lardan',
  getParentRoute: () => rootRouteImport,
} as any)
const SemijoiasRoute = SemijoiasRouteImport.update({
  id: '/semijoias',
  path: '/semijoias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SemijoiasAneisRoute = SemijoiasAneisRouteImport.update({
  id: '/aneis',
  path: '/aneis',
  getParentRoute: () => SemijoiasRoute,
} as any)
const SemijoiasColaresRoute = SemijoiasColaresRouteImport.update({
  id: '/colares',
  path: '/colares',
  getParentRoute: () => SemijoiasRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportacaoRoute =
  AuthenticatedAdminImportacaoRouteImport.update({
    id: '/importacao',
    path: '/importacao',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSiteRoute = AuthenticatedAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosIndexRoute =
  AuthenticatedAdminCadastrosIndexRouteImport.update({
    id: '/cadastros/',
    path: '/cadastros/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosCategoriasRoute =
  AuthenticatedAdminCadastrosCategoriasRouteImport.update({
    id: '/cadastros/categorias',
    path: '/cadastros/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosColecoesRoute =
  AuthenticatedAdminCadastrosColecoesRouteImport.update({
    id: '/cadastros/colecoes',
    path: '/cadastros/colecoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosEntidadesRoute =
  AuthenticatedAdminCadastrosEntidadesRouteImport.update({
    id: '/cadastros/entidades',
    path: '/cadastros/entidades',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosFornecedoresRoute =
  AuthenticatedAdminCadastrosFornecedoresRouteImport.update({
    id: '/cadastros/fornecedores',
    path: '/cadastros/fornecedores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosLocaisRoute =
  AuthenticatedAdminCadastrosLocaisRouteImport.update({
    id: '/cadastros/locais',
    path: '/cadastros/locais',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-lardan': typeof ALardanRoute
  '/acesso': typeof AcessoRoute
  '/colecoes': typeof ColecoesRoute
  '/contato': typeof ContatoRoute
  '/seja-lardan': typeof SejaLardanRoute
  '/semijoias': typeof SemijoiasRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/semijoias/aneis': typeof SemijoiasAneisRoute
  '/semijoias/colares': typeof SemijoiasColaresRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cadastros/categorias': typeof AuthenticatedAdminCadastrosCategoriasRoute
  '/admin/cadastros/colecoes': typeof AuthenticatedAdminCadastrosColecoesRoute
  '/admin/cadastros/entidades': typeof AuthenticatedAdminCadastrosEntidadesRoute
  '/admin/cadastros/fornecedores': typeof AuthenticatedAdminCadastrosFornecedoresRoute
  '/admin/cadastros/locais': typeof AuthenticatedAdminCadastrosLocaisRoute
  '/admin/cadastros/': typeof AuthenticatedAdminCadastrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-lardan': typeof ALardanRoute
  '/acesso': typeof AcessoRoute
  '/colecoes': typeof ColecoesRoute
  '/contato': typeof ContatoRoute
  '/seja-lardan': typeof SejaLardanRoute
  '/semijoias': typeof SemijoiasRouteWithChildren
  '/semijoias/aneis': typeof SemijoiasAneisRoute
  '/semijoias/colares': typeof SemijoiasColaresRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cadastros/categorias': typeof AuthenticatedAdminCadastrosCategoriasRoute
  '/admin/cadastros/colecoes': typeof AuthenticatedAdminCadastrosColecoesRoute
  '/admin/cadastros/entidades': typeof AuthenticatedAdminCadastrosEntidadesRoute
  '/admin/cadastros/fornecedores': typeof AuthenticatedAdminCadastrosFornecedoresRoute
  '/admin/cadastros/locais': typeof AuthenticatedAdminCadastrosLocaisRoute
  '/admin/cadastros': typeof AuthenticatedAdminCadastrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-lardan': typeof ALardanRoute
  '/acesso': typeof AcessoRoute
  '/colecoes': typeof ColecoesRoute
  '/contato': typeof ContatoRoute
  '/seja-lardan': typeof SejaLardanRoute
  '/semijoias': typeof SemijoiasRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/semijoias/aneis': typeof SemijoiasAneisRoute
  '/semijoias/colares': typeof SemijoiasColaresRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/site': typeof AuthenticatedAdminSiteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cadastros/categorias': typeof AuthenticatedAdminCadastrosCategoriasRoute
  '/_authenticated/admin/cadastros/colecoes': typeof AuthenticatedAdminCadastrosColecoesRoute
  '/_authenticated/admin/cadastros/entidades': typeof AuthenticatedAdminCadastrosEntidadesRoute
  '/_authenticated/admin/cadastros/fornecedores': typeof AuthenticatedAdminCadastrosFornecedoresRoute
  '/_authenticated/admin/cadastros/locais': typeof AuthenticatedAdminCadastrosLocaisRoute
  '/_authenticated/admin/cadastros/': typeof AuthenticatedAdminCadastrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-lardan'
    | '/acesso'
    | '/colecoes'
    | '/contato'
    | '/seja-lardan'
    | '/semijoias'
    | '/admin'
    | '/semijoias/aneis'
    | '/semijoias/colares'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/importacao'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/site'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/cadastros/categorias'
    | '/admin/cadastros/colecoes'
    | '/admin/cadastros/entidades'
    | '/admin/cadastros/fornecedores'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-lardan'
    | '/acesso'
    | '/colecoes'
    | '/contato'
    | '/seja-lardan'
    | '/semijoias'
    | '/semijoias/aneis'
    | '/semijoias/colares'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/importacao'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/site'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/cadastros/categorias'
    | '/admin/cadastros/colecoes'
    | '/admin/cadastros/entidades'
    | '/admin/cadastros/fornecedores'
    | '/admin/cadastros/locais'
    | '/admin/cadastros'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-lardan'
    | '/acesso'
    | '/colecoes'
    | '/contato'
    | '/seja-lardan'
    | '/semijoias'
    | '/_authenticated/admin'
    | '/semijoias/aneis'
    | '/semijoias/colares'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/importacao'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/site'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cadastros/categorias'
    | '/_authenticated/admin/cadastros/colecoes'
    | '/_authenticated/admin/cadastros/entidades'
    | '/_authenticated/admin/cadastros/fornecedores'
    | '/_authenticated/admin/cadastros/locais'
    | '/_authenticated/admin/cadastros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ALardanRoute: typeof ALardanRoute
  AcessoRoute: typeof AcessoRoute
  ColecoesRoute: typeof ColecoesRoute
  ContatoRoute: typeof ContatoRoute
  SejaLardanRoute: typeof SejaLardanRoute
  SemijoiasRoute: typeof SemijoiasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-lardan': {
      id: '/a-lardan'
      path: '/a-lardan'
      fullPath: '/a-lardan'
      preLoaderRoute: typeof ALardanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes': {
      id: '/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof ColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-lardan': {
      id: '/seja-lardan'
      path: '/seja-lardan'
      fullPath: '/seja-lardan'
      preLoaderRoute: typeof SejaLardanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semijoias': {
      id: '/semijoias'
      path: '/semijoias'
      fullPath: '/semijoias'
      preLoaderRoute: typeof SemijoiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/semijoias/aneis': {
      id: '/semijoias/aneis'
      path: '/aneis'
      fullPath: '/semijoias/aneis'
      preLoaderRoute: typeof SemijoiasAneisRouteImport
      parentRoute: typeof SemijoiasRoute
    }
    '/semijoias/colares': {
      id: '/semijoias/colares'
      path: '/colares'
      fullPath: '/semijoias/colares'
      preLoaderRoute: typeof SemijoiasColaresRouteImport
      parentRoute: typeof SemijoiasRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/importacao': {
      id: '/_authenticated/admin/importacao'
      path: '/importacao'
      fullPath: '/admin/importacao'
      preLoaderRoute: typeof AuthenticatedAdminImportacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/site': {
      id: '/_authenticated/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AuthenticatedAdminSiteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/': {
      id: '/_authenticated/admin/cadastros/'
      path: '/cadastros'
      fullPath: '/admin/cadastros/'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/categorias': {
      id: '/_authenticated/admin/cadastros/categorias'
      path: '/cadastros/categorias'
      fullPath: '/admin/cadastros/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/colecoes': {
      id: '/_authenticated/admin/cadastros/colecoes'
      path: '/cadastros/colecoes'
      fullPath: '/admin/cadastros/colecoes'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosColecoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/entidades': {
      id: '/_authenticated/admin/cadastros/entidades'
      path: '/cadastros/entidades'
      fullPath: '/admin/cadastros/entidades'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosEntidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/fornecedores': {
      id: '/_authenticated/admin/cadastros/fornecedores'
      path: '/cadastros/fornecedores'
      fullPath: '/admin/cadastros/fornecedores'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosFornecedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/locais': {
      id: '/_authenticated/admin/cadastros/locais'
      path: '/cadastros/locais'
      fullPath: '/admin/cadastros/locais'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosLocaisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminImportacaoRoute: typeof AuthenticatedAdminImportacaoRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminSiteRoute: typeof AuthenticatedAdminSiteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCadastrosCategoriasRoute: typeof AuthenticatedAdminCadastrosCategoriasRoute
  AuthenticatedAdminCadastrosColecoesRoute: typeof AuthenticatedAdminCadastrosColecoesRoute
  AuthenticatedAdminCadastrosEntidadesRoute: typeof AuthenticatedAdminCadastrosEntidadesRoute
  AuthenticatedAdminCadastrosFornecedoresRoute: typeof AuthenticatedAdminCadastrosFornecedoresRoute
  AuthenticatedAdminCadastrosLocaisRoute: typeof AuthenticatedAdminCadastrosLocaisRoute
  AuthenticatedAdminCadastrosIndexRoute: typeof AuthenticatedAdminCadastrosIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
    AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
    AuthenticatedAdminImportacaoRoute: AuthenticatedAdminImportacaoRoute,
    AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
    AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
    AuthenticatedAdminSiteRoute: AuthenticatedAdminSiteRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCadastrosCategoriasRoute:
      AuthenticatedAdminCadastrosCategoriasRoute,
    AuthenticatedAdminCadastrosColecoesRoute:
      AuthenticatedAdminCadastrosColecoesRoute,
    AuthenticatedAdminCadastrosEntidadesRoute:
      AuthenticatedAdminCadastrosEntidadesRoute,
    AuthenticatedAdminCadastrosFornecedoresRoute:
      AuthenticatedAdminCadastrosFornecedoresRoute,
    AuthenticatedAdminCadastrosLocaisRoute:
      AuthenticatedAdminCadastrosLocaisRoute,
    AuthenticatedAdminCadastrosIndexRoute:
      AuthenticatedAdminCadastrosIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SemijoiasRouteChildren {
  SemijoiasAneisRoute: typeof SemijoiasAneisRoute
  SemijoiasColaresRoute: typeof SemijoiasColaresRoute
}

const SemijoiasRouteChildren: SemijoiasRouteChildren = {
  SemijoiasAneisRoute: SemijoiasAneisRoute,
  SemijoiasColaresRoute: SemijoiasColaresRoute,
}

const SemijoiasRouteWithChildren = SemijoiasRoute._addFileChildren(
  SemijoiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ALardanRoute: ALardanRoute,
  AcessoRoute: AcessoRoute,
  ColecoesRoute: ColecoesRoute,
  ContatoRoute: ContatoRoute,
  SejaLardanRoute: SejaLardanRoute,
  SemijoiasRoute: SemijoiasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
