/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ALardanRouteImport } from './routes/a-lardan'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AneisRouteImport } from './routes/aneis'
import { Route as BrincosRouteImport } from './routes/brincos'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ColaresRouteImport } from './routes/colares'
import { Route as ColecoesRouteImport } from './routes/colecoes'
import { Route as ComoComecarAVenderSemijoiasRouteImport } from './routes/como-comecar-a-vender-semijoias'
import { Route as ComoVenderSemijoiasPeloWhatsappRouteImport } from './routes/como-vender-semijoias-pelo-whatsapp'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PulseirasRouteImport } from './routes/pulseiras'
import { Route as RendaExtraComVendasRouteImport } from './routes/renda-extra-com-vendas'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SejaLardanRouteImport } from './routes/seja-lardan'
import { Route as SemijoiasConsignadasParaRevendaRouteImport } from './routes/semijoias-consignadas-para-revenda'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedConsultoraRouteImport } from './routes/_authenticated/consultora'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as SemijoiasIndexRouteImport } from './routes/semijoias.index'
import { Route as SemijoiasCategoriaRouteImport } from './routes/semijoias.$categoria'
import { Route as SitemapProductsPaginaRouteImport } from './routes/sitemap-products.$pagina'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedAdminCandidaturasRouteImport } from './routes/_authenticated/admin/candidaturas'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin/estoque'
import { Route as AuthenticatedAdminFinanceiroRouteRouteImport } from './routes/_authenticated/admin/financeiro/route'
import { Route as AuthenticatedAdminImportacaoRouteImport } from './routes/_authenticated/admin/importacao'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin/integracoes'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminMaletasRouteImport } from './routes/_authenticated/admin/maletas'
import { Route as AuthenticatedAdminPerfilRouteImport } from './routes/_authenticated/admin/perfil'
import { Route as AuthenticatedAdminRedeRouteImport } from './routes/_authenticated/admin/rede'
import { Route as AuthenticatedAdminSiteRouteImport } from './routes/_authenticated/admin/site'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as ApiPublicGaConfigRouteImport } from './routes/api/public/ga-config'
import { Route as AuthenticatedAdminCadastrosIndexRouteImport } from './routes/_authenticated/admin/cadastros/index'
import { Route as AuthenticatedAdminCadastrosCategoriasRouteImport } from './routes/_authenticated/admin/cadastros/categorias'
import { Route as AuthenticatedAdminCadastrosColecoesRouteImport } from './routes/_authenticated/admin/cadastros/colecoes'
import { Route as AuthenticatedAdminCadastrosDuplicidadesRouteImport } from './routes/_authenticated/admin/cadastros/duplicidades'
import { Route as AuthenticatedAdminCadastrosEntidadesRouteImport } from './routes/_authenticated/admin/cadastros/entidades'
import { Route as AuthenticatedAdminCadastrosFornecedoresRouteImport } from './routes/_authenticated/admin/cadastros/fornecedores'
import { Route as AuthenticatedAdminCadastrosLocaisRouteImport } from './routes/_authenticated/admin/cadastros/locais'
import { Route as AuthenticatedAdminCadastrosPessoasRouteImport } from './routes/_authenticated/admin/cadastros/pessoas'
import { Route as AuthenticatedAdminCadastrosProdutosRouteImport } from './routes/_authenticated/admin/cadastros/produtos'
import { Route as AuthenticatedAdminCandidaturasIdRouteImport } from './routes/_authenticated/admin/candidaturas_.$id'
import { Route as AuthenticatedAdminFinanceiroIndexRouteImport } from './routes/_authenticated/admin/financeiro/index'
import { Route as AuthenticatedAdminFinanceiroAprovacoesRouteImport } from './routes/_authenticated/admin/financeiro/aprovacoes'
import { Route as AuthenticatedAdminFinanceiroAuditoriaRouteImport } from './routes/_authenticated/admin/financeiro/auditoria'
import { Route as AuthenticatedAdminFinanceiroCentrosCustoRouteImport } from './routes/_authenticated/admin/financeiro/centros-custo'
import { Route as AuthenticatedAdminFinanceiroConciliacaoRouteImport } from './routes/_authenticated/admin/financeiro/conciliacao'
import { Route as AuthenticatedAdminFinanceiroConfiguracoesRouteImport } from './routes/_authenticated/admin/financeiro/configuracoes'
import { Route as AuthenticatedAdminFinanceiroContasRouteImport } from './routes/_authenticated/admin/financeiro/contas'
import { Route as AuthenticatedAdminFinanceiroDreRouteImport } from './routes/_authenticated/admin/financeiro/dre'
import { Route as AuthenticatedAdminFinanceiroFluxoCaixaRouteImport } from './routes/_authenticated/admin/financeiro/fluxo-caixa'
import { Route as AuthenticatedAdminFinanceiroImportacoesRouteImport } from './routes/_authenticated/admin/financeiro/importacoes'
import { Route as AuthenticatedAdminFinanceiroPagarRouteImport } from './routes/_authenticated/admin/financeiro/pagar'
import { Route as AuthenticatedAdminFinanceiroPlanoContasRouteImport } from './routes/_authenticated/admin/financeiro/plano-contas'
import { Route as AuthenticatedAdminFinanceiroReceberRouteImport } from './routes/_authenticated/admin/financeiro/receber'
import { Route as AuthenticatedAdminMaletasIdRouteImport } from './routes/_authenticated/admin/maletas_.$id'
import { Route as ApiPublicMidiaIdRouteImport } from './routes/api/public/midia.$id'
import { Route as AuthenticatedAdminCadastrosPessoasIdRouteImport } from './routes/_authenticated/admin/cadastros/pessoas_.$id'
import { Route as AuthenticatedAdminCadastrosPessoasNovoRouteImport } from './routes/_authenticated/admin/cadastros/pessoas_.novo'
import { Route as AuthenticatedAdminCadastrosProdutosIdRouteImport } from './routes/_authenticated/admin/cadastros/produtos_.$id'
import { Route as AuthenticatedAdminCadastrosProdutosNovoRouteImport } from './routes/_authenticated/admin/cadastros/produtos_.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ALardanRoute = ALardanRouteImport.update({
  id: '/a-lardan',
  path: '/a-lardan',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AneisRoute = AneisRouteImport.update({
  id: '/aneis',
  path: '/aneis',
  getParentRoute: () => rootRouteImport,
} as any)
const BrincosRoute = BrincosRouteImport.update({
  id: '/brincos',
  path: '/brincos',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaresRoute = ColaresRouteImport.update({
  id: '/colares',
  path: '/colares',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesRoute = ColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoComecarAVenderSemijoiasRoute =
  ComoComecarAVenderSemijoiasRouteImport.update({
    id: '/como-comecar-a-vender-semijoias',
    path: '/como-comecar-a-vender-semijoias',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComoVenderSemijoiasPeloWhatsappRoute =
  ComoVenderSemijoiasPeloWhatsappRouteImport.update({
    id: '/como-vender-semijoias-pelo-whatsapp',
    path: '/como-vender-semijoias-pelo-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseirasRoute = PulseirasRouteImport.update({
  id: '/pulseiras',
  path: '/pulseiras',
  getParentRoute: () => rootRouteImport,
} as any)
const RendaExtraComVendasRoute = RendaExtraComVendasRouteImport.update({
  id: '/renda-extra-com-vendas',
  path: '/renda-extra-com-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaLardanRoute = SejaLardanRouteImport.update({
  id: '/seja-lardan',
  path: '/seja-lardan',
  getParentRoute: () => rootRouteImport,
} as any)
const SemijoiasConsignadasParaRevendaRoute =
  SemijoiasConsignadasParaRevendaRouteImport.update({
    id: '/semijoias-consignadas-para-revenda',
    path: '/semijoias-consignadas-para-revenda',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultoraRoute = AuthenticatedConsultoraRouteImport.update({
  id: '/consultora',
  path: '/consultora',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SemijoiasIndexRoute = SemijoiasIndexRouteImport.update({
  id: '/semijoias/',
  path: '/semijoias/',
  getParentRoute: () => rootRouteImport,
} as any)
const SemijoiasCategoriaRoute = SemijoiasCategoriaRouteImport.update({
  id: '/semijoias/$categoria',
  path: '/semijoias/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProductsPaginaRoute = SitemapProductsPaginaRouteImport.update({
  id: '/sitemap-products/$pagina',
  path: '/sitemap-products/$pagina',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCandidaturasRoute =
  AuthenticatedAdminCandidaturasRouteImport.update({
    id: '/candidaturas',
    path: '/candidaturas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroRouteRoute =
  AuthenticatedAdminFinanceiroRouteRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportacaoRoute =
  AuthenticatedAdminImportacaoRouteImport.update({
    id: '/importacao',
    path: '/importacao',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMaletasRoute =
  AuthenticatedAdminMaletasRouteImport.update({
    id: '/maletas',
    path: '/maletas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPerfilRoute =
  AuthenticatedAdminPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRedeRoute = AuthenticatedAdminRedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSiteRoute = AuthenticatedAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicGaConfigRoute = ApiPublicGaConfigRouteImport.update({
  id: '/api/public/ga-config',
  path: '/api/public/ga-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCadastrosIndexRoute =
  AuthenticatedAdminCadastrosIndexRouteImport.update({
    id: '/cadastros/',
    path: '/cadastros/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosCategoriasRoute =
  AuthenticatedAdminCadastrosCategoriasRouteImport.update({
    id: '/cadastros/categorias',
    path: '/cadastros/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosColecoesRoute =
  AuthenticatedAdminCadastrosColecoesRouteImport.update({
    id: '/cadastros/colecoes',
    path: '/cadastros/colecoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosDuplicidadesRoute =
  AuthenticatedAdminCadastrosDuplicidadesRouteImport.update({
    id: '/cadastros/duplicidades',
    path: '/cadastros/duplicidades',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosEntidadesRoute =
  AuthenticatedAdminCadastrosEntidadesRouteImport.update({
    id: '/cadastros/entidades',
    path: '/cadastros/entidades',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosFornecedoresRoute =
  AuthenticatedAdminCadastrosFornecedoresRouteImport.update({
    id: '/cadastros/fornecedores',
    path: '/cadastros/fornecedores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosLocaisRoute =
  AuthenticatedAdminCadastrosLocaisRouteImport.update({
    id: '/cadastros/locais',
    path: '/cadastros/locais',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosPessoasRoute =
  AuthenticatedAdminCadastrosPessoasRouteImport.update({
    id: '/cadastros/pessoas',
    path: '/cadastros/pessoas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosProdutosRoute =
  AuthenticatedAdminCadastrosProdutosRouteImport.update({
    id: '/cadastros/produtos',
    path: '/cadastros/produtos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCandidaturasIdRoute =
  AuthenticatedAdminCandidaturasIdRouteImport.update({
    id: '/candidaturas_/$id',
    path: '/candidaturas/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroIndexRoute =
  AuthenticatedAdminFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroAprovacoesRoute =
  AuthenticatedAdminFinanceiroAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroAuditoriaRoute =
  AuthenticatedAdminFinanceiroAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroCentrosCustoRoute =
  AuthenticatedAdminFinanceiroCentrosCustoRouteImport.update({
    id: '/centros-custo',
    path: '/centros-custo',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroConciliacaoRoute =
  AuthenticatedAdminFinanceiroConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroConfiguracoesRoute =
  AuthenticatedAdminFinanceiroConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroContasRoute =
  AuthenticatedAdminFinanceiroContasRouteImport.update({
    id: '/contas',
    path: '/contas',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroDreRoute =
  AuthenticatedAdminFinanceiroDreRouteImport.update({
    id: '/dre',
    path: '/dre',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroFluxoCaixaRoute =
  AuthenticatedAdminFinanceiroFluxoCaixaRouteImport.update({
    id: '/fluxo-caixa',
    path: '/fluxo-caixa',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroImportacoesRoute =
  AuthenticatedAdminFinanceiroImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroPagarRoute =
  AuthenticatedAdminFinanceiroPagarRouteImport.update({
    id: '/pagar',
    path: '/pagar',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroPlanoContasRoute =
  AuthenticatedAdminFinanceiroPlanoContasRouteImport.update({
    id: '/plano-contas',
    path: '/plano-contas',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroReceberRoute =
  AuthenticatedAdminFinanceiroReceberRouteImport.update({
    id: '/receber',
    path: '/receber',
    getParentRoute: () => AuthenticatedAdminFinanceiroRouteRoute,
  } as any)
const AuthenticatedAdminMaletasIdRoute =
  AuthenticatedAdminMaletasIdRouteImport.update({
    id: '/maletas_/$id',
    path: '/maletas/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicMidiaIdRoute = ApiPublicMidiaIdRouteImport.update({
  id: '/api/public/midia/$id',
  path: '/api/public/midia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCadastrosPessoasIdRoute =
  AuthenticatedAdminCadastrosPessoasIdRouteImport.update({
    id: '/cadastros/pessoas_/$id',
    path: '/cadastros/pessoas/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosPessoasNovoRoute =
  AuthenticatedAdminCadastrosPessoasNovoRouteImport.update({
    id: '/cadastros/pessoas_/novo',
    path: '/cadastros/pessoas/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosProdutosIdRoute =
  AuthenticatedAdminCadastrosProdutosIdRouteImport.update({
    id: '/cadastros/produtos_/$id',
    path: '/cadastros/produtos/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosProdutosNovoRoute =
  AuthenticatedAdminCadastrosProdutosNovoRouteImport.update({
    id: '/cadastros/produtos_/novo',
    path: '/cadastros/produtos/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/a-lardan': typeof ALardanRoute
  '/acesso': typeof AcessoRoute
  '/aneis': typeof AneisRoute
  '/brincos': typeof BrincosRoute
  '/carrinho': typeof CarrinhoRoute
  '/colares': typeof ColaresRoute
  '/colecoes': typeof ColecoesRoute
  '/como-comecar-a-vender-semijoias': typeof ComoComecarAVenderSemijoiasRoute
  '/como-vender-semijoias-pelo-whatsapp': typeof ComoVenderSemijoiasPeloWhatsappRoute
  '/contato': typeof ContatoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pulseiras': typeof PulseirasRoute
  '/renda-extra-com-vendas': typeof RendaExtraComVendasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seja-lardan': typeof SejaLardanRoute
  '/semijoias-consignadas-para-revenda': typeof SemijoiasConsignadasParaRevendaRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/consultora': typeof AuthenticatedConsultoraRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/semijoias/$categoria': typeof SemijoiasCategoriaRoute
  '/sitemap-products/$pagina': typeof SitemapProductsPaginaRoute
  '/semijoias/': typeof SemijoiasIndexRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRouteRouteWithChildren
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/candidaturas': typeof AuthenticatedAdminCandidaturasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/maletas': typeof AuthenticatedAdminMaletasRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/rede': typeof AuthenticatedAdminRedeRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/ga-config': typeof ApiPublicGaConfigRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cadastros/categorias': typeof AuthenticatedAdminCadastrosCategoriasRoute
  '/admin/cadastros/colecoes': typeof AuthenticatedAdminCadastrosColecoesRoute
  '/admin/cadastros/duplicidades': typeof AuthenticatedAdminCadastrosDuplicidadesRoute
  '/admin/cadastros/entidades': typeof AuthenticatedAdminCadastrosEntidadesRoute
  '/admin/cadastros/fornecedores': typeof AuthenticatedAdminCadastrosFornecedoresRoute
  '/admin/cadastros/locais': typeof AuthenticatedAdminCadastrosLocaisRoute
  '/admin/cadastros/pessoas': typeof AuthenticatedAdminCadastrosPessoasRoute
  '/admin/cadastros/produtos': typeof AuthenticatedAdminCadastrosProdutosRoute
  '/admin/candidaturas/$id': typeof AuthenticatedAdminCandidaturasIdRoute
  '/admin/financeiro/aprovacoes': typeof AuthenticatedAdminFinanceiroAprovacoesRoute
  '/admin/financeiro/auditoria': typeof AuthenticatedAdminFinanceiroAuditoriaRoute
  '/admin/financeiro/centros-custo': typeof AuthenticatedAdminFinanceiroCentrosCustoRoute
  '/admin/financeiro/conciliacao': typeof AuthenticatedAdminFinanceiroConciliacaoRoute
  '/admin/financeiro/configuracoes': typeof AuthenticatedAdminFinanceiroConfiguracoesRoute
  '/admin/financeiro/contas': typeof AuthenticatedAdminFinanceiroContasRoute
  '/admin/financeiro/dre': typeof AuthenticatedAdminFinanceiroDreRoute
  '/admin/financeiro/fluxo-caixa': typeof AuthenticatedAdminFinanceiroFluxoCaixaRoute
  '/admin/financeiro/importacoes': typeof AuthenticatedAdminFinanceiroImportacoesRoute
  '/admin/financeiro/pagar': typeof AuthenticatedAdminFinanceiroPagarRoute
  '/admin/financeiro/plano-contas': typeof AuthenticatedAdminFinanceiroPlanoContasRoute
  '/admin/financeiro/receber': typeof AuthenticatedAdminFinanceiroReceberRoute
  '/admin/maletas/$id': typeof AuthenticatedAdminMaletasIdRoute
  '/api/public/midia/$id': typeof ApiPublicMidiaIdRoute
  '/admin/cadastros/': typeof AuthenticatedAdminCadastrosIndexRoute
  '/admin/financeiro/': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/admin/cadastros/pessoas/$id': typeof AuthenticatedAdminCadastrosPessoasIdRoute
  '/admin/cadastros/pessoas/novo': typeof AuthenticatedAdminCadastrosPessoasNovoRoute
  '/admin/cadastros/produtos/$id': typeof AuthenticatedAdminCadastrosProdutosIdRoute
  '/admin/cadastros/produtos/novo': typeof AuthenticatedAdminCadastrosProdutosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/a-lardan': typeof ALardanRoute
  '/acesso': typeof AcessoRoute
  '/aneis': typeof AneisRoute
  '/brincos': typeof BrincosRoute
  '/carrinho': typeof CarrinhoRoute
  '/colares': typeof ColaresRoute
  '/colecoes': typeof ColecoesRoute
  '/como-comecar-a-vender-semijoias': typeof ComoComecarAVenderSemijoiasRoute
  '/como-vender-semijoias-pelo-whatsapp': typeof ComoVenderSemijoiasPeloWhatsappRoute
  '/contato': typeof ContatoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pulseiras': typeof PulseirasRoute
  '/renda-extra-com-vendas': typeof RendaExtraComVendasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seja-lardan': typeof SejaLardanRoute
  '/semijoias-consignadas-para-revenda': typeof SemijoiasConsignadasParaRevendaRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/consultora': typeof AuthenticatedConsultoraRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/semijoias/$categoria': typeof SemijoiasCategoriaRoute
  '/sitemap-products/$pagina': typeof SitemapProductsPaginaRoute
  '/semijoias': typeof SemijoiasIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/candidaturas': typeof AuthenticatedAdminCandidaturasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/maletas': typeof AuthenticatedAdminMaletasRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/rede': typeof AuthenticatedAdminRedeRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/ga-config': typeof ApiPublicGaConfigRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cadastros/categorias': typeof AuthenticatedAdminCadastrosCategoriasRoute
  '/admin/cadastros/colecoes': typeof AuthenticatedAdminCadastrosColecoesRoute
  '/admin/cadastros/duplicidades': typeof AuthenticatedAdminCadastrosDuplicidadesRoute
  '/admin/cadastros/entidades': typeof AuthenticatedAdminCadastrosEntidadesRoute
  '/admin/cadastros/fornecedores': typeof AuthenticatedAdminCadastrosFornecedoresRoute
  '/admin/cadastros/locais': typeof AuthenticatedAdminCadastrosLocaisRoute
  '/admin/cadastros/pessoas': typeof AuthenticatedAdminCadastrosPessoasRoute
  '/admin/cadastros/produtos': typeof AuthenticatedAdminCadastrosProdutosRoute
  '/admin/candidaturas/$id': typeof AuthenticatedAdminCandidaturasIdRoute
  '/admin/financeiro/aprovacoes': typeof AuthenticatedAdminFinanceiroAprovacoesRoute
  '/admin/financeiro/auditoria': typeof AuthenticatedAdminFinanceiroAuditoriaRoute
  '/admin/financeiro/centros-custo': typeof AuthenticatedAdminFinanceiroCentrosCustoRoute
  '/admin/financeiro/conciliacao': typeof AuthenticatedAdminFinanceiroConciliacaoRoute
  '/admin/financeiro/configuracoes': typeof AuthenticatedAdminFinanceiroConfiguracoesRoute
  '/admin/financeiro/contas': typeof AuthenticatedAdminFinanceiroContasRoute
  '/admin/financeiro/dre': typeof AuthenticatedAdminFinanceiroDreRoute
  '/admin/financeiro/fluxo-caixa': typeof AuthenticatedAdminFinanceiroFluxoCaixaRoute
  '/admin/financeiro/importacoes': typeof AuthenticatedAdminFinanceiroImportacoesRoute
  '/admin/financeiro/pagar': typeof AuthenticatedAdminFinanceiroPagarRoute
  '/admin/financeiro/plano-contas': typeof AuthenticatedAdminFinanceiroPlanoContasRoute
  '/admin/financeiro/receber': typeof AuthenticatedAdminFinanceiroReceberRoute
  '/admin/maletas/$id': typeof AuthenticatedAdminMaletasIdRoute
  '/api/public/midia/$id': typeof ApiPublicMidiaIdRoute
  '/admin/cadastros': typeof AuthenticatedAdminCadastrosIndexRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/admin/cadastros/pessoas/$id': typeof AuthenticatedAdminCadastrosPessoasIdRoute
  '/admin/cadastros/pessoas/novo': typeof AuthenticatedAdminCadastrosPessoasNovoRoute
  '/admin/cadastros/produtos/$id': typeof AuthenticatedAdminCadastrosProdutosIdRoute
  '/admin/cadastros/produtos/novo': typeof AuthenticatedAdminCadastrosProdutosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/a-lardan': typeof ALardanRoute
  '/acesso': typeof AcessoRoute
  '/aneis': typeof AneisRoute
  '/brincos': typeof BrincosRoute
  '/carrinho': typeof CarrinhoRoute
  '/colares': typeof ColaresRoute
  '/colecoes': typeof ColecoesRoute
  '/como-comecar-a-vender-semijoias': typeof ComoComecarAVenderSemijoiasRoute
  '/como-vender-semijoias-pelo-whatsapp': typeof ComoVenderSemijoiasPeloWhatsappRoute
  '/contato': typeof ContatoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pulseiras': typeof PulseirasRoute
  '/renda-extra-com-vendas': typeof RendaExtraComVendasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seja-lardan': typeof SejaLardanRoute
  '/semijoias-consignadas-para-revenda': typeof SemijoiasConsignadasParaRevendaRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/consultora': typeof AuthenticatedConsultoraRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/semijoias/$categoria': typeof SemijoiasCategoriaRoute
  '/sitemap-products/$pagina': typeof SitemapProductsPaginaRoute
  '/semijoias/': typeof SemijoiasIndexRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRouteRouteWithChildren
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/candidaturas': typeof AuthenticatedAdminCandidaturasRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/maletas': typeof AuthenticatedAdminMaletasRoute
  '/_authenticated/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/_authenticated/admin/rede': typeof AuthenticatedAdminRedeRoute
  '/_authenticated/admin/site': typeof AuthenticatedAdminSiteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/ga-config': typeof ApiPublicGaConfigRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cadastros/categorias': typeof AuthenticatedAdminCadastrosCategoriasRoute
  '/_authenticated/admin/cadastros/colecoes': typeof AuthenticatedAdminCadastrosColecoesRoute
  '/_authenticated/admin/cadastros/duplicidades': typeof AuthenticatedAdminCadastrosDuplicidadesRoute
  '/_authenticated/admin/cadastros/entidades': typeof AuthenticatedAdminCadastrosEntidadesRoute
  '/_authenticated/admin/cadastros/fornecedores': typeof AuthenticatedAdminCadastrosFornecedoresRoute
  '/_authenticated/admin/cadastros/locais': typeof AuthenticatedAdminCadastrosLocaisRoute
  '/_authenticated/admin/cadastros/pessoas': typeof AuthenticatedAdminCadastrosPessoasRoute
  '/_authenticated/admin/cadastros/produtos': typeof AuthenticatedAdminCadastrosProdutosRoute
  '/_authenticated/admin/candidaturas_/$id': typeof AuthenticatedAdminCandidaturasIdRoute
  '/_authenticated/admin/financeiro/aprovacoes': typeof AuthenticatedAdminFinanceiroAprovacoesRoute
  '/_authenticated/admin/financeiro/auditoria': typeof AuthenticatedAdminFinanceiroAuditoriaRoute
  '/_authenticated/admin/financeiro/centros-custo': typeof AuthenticatedAdminFinanceiroCentrosCustoRoute
  '/_authenticated/admin/financeiro/conciliacao': typeof AuthenticatedAdminFinanceiroConciliacaoRoute
  '/_authenticated/admin/financeiro/configuracoes': typeof AuthenticatedAdminFinanceiroConfiguracoesRoute
  '/_authenticated/admin/financeiro/contas': typeof AuthenticatedAdminFinanceiroContasRoute
  '/_authenticated/admin/financeiro/dre': typeof AuthenticatedAdminFinanceiroDreRoute
  '/_authenticated/admin/financeiro/fluxo-caixa': typeof AuthenticatedAdminFinanceiroFluxoCaixaRoute
  '/_authenticated/admin/financeiro/importacoes': typeof AuthenticatedAdminFinanceiroImportacoesRoute
  '/_authenticated/admin/financeiro/pagar': typeof AuthenticatedAdminFinanceiroPagarRoute
  '/_authenticated/admin/financeiro/plano-contas': typeof AuthenticatedAdminFinanceiroPlanoContasRoute
  '/_authenticated/admin/financeiro/receber': typeof AuthenticatedAdminFinanceiroReceberRoute
  '/_authenticated/admin/maletas_/$id': typeof AuthenticatedAdminMaletasIdRoute
  '/api/public/midia/$id': typeof ApiPublicMidiaIdRoute
  '/_authenticated/admin/cadastros/': typeof AuthenticatedAdminCadastrosIndexRoute
  '/_authenticated/admin/financeiro/': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/_authenticated/admin/cadastros/pessoas_/$id': typeof AuthenticatedAdminCadastrosPessoasIdRoute
  '/_authenticated/admin/cadastros/pessoas_/novo': typeof AuthenticatedAdminCadastrosPessoasNovoRoute
  '/_authenticated/admin/cadastros/produtos_/$id': typeof AuthenticatedAdminCadastrosProdutosIdRoute
  '/_authenticated/admin/cadastros/produtos_/novo': typeof AuthenticatedAdminCadastrosProdutosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/a-lardan'
    | '/acesso'
    | '/aneis'
    | '/brincos'
    | '/carrinho'
    | '/colares'
    | '/colecoes'
    | '/como-comecar-a-vender-semijoias'
    | '/como-vender-semijoias-pelo-whatsapp'
    | '/contato'
    | '/llms.txt'
    | '/pulseiras'
    | '/renda-extra-com-vendas'
    | '/robots.txt'
    | '/seja-lardan'
    | '/semijoias-consignadas-para-revenda'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/admin'
    | '/consultora'
    | '/produto/$slug'
    | '/semijoias/$categoria'
    | '/sitemap-products/$pagina'
    | '/semijoias/'
    | '/admin/financeiro'
    | '/admin/auditoria'
    | '/admin/candidaturas'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/importacao'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/maletas'
    | '/admin/perfil'
    | '/admin/rede'
    | '/admin/site'
    | '/admin/usuarios'
    | '/api/public/ga-config'
    | '/admin/'
    | '/admin/cadastros/categorias'
    | '/admin/cadastros/colecoes'
    | '/admin/cadastros/duplicidades'
    | '/admin/cadastros/entidades'
    | '/admin/cadastros/fornecedores'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/pessoas'
    | '/admin/cadastros/produtos'
    | '/admin/candidaturas/$id'
    | '/admin/financeiro/aprovacoes'
    | '/admin/financeiro/auditoria'
    | '/admin/financeiro/centros-custo'
    | '/admin/financeiro/conciliacao'
    | '/admin/financeiro/configuracoes'
    | '/admin/financeiro/contas'
    | '/admin/financeiro/dre'
    | '/admin/financeiro/fluxo-caixa'
    | '/admin/financeiro/importacoes'
    | '/admin/financeiro/pagar'
    | '/admin/financeiro/plano-contas'
    | '/admin/financeiro/receber'
    | '/admin/maletas/$id'
    | '/api/public/midia/$id'
    | '/admin/cadastros/'
    | '/admin/financeiro/'
    | '/admin/cadastros/pessoas/$id'
    | '/admin/cadastros/pessoas/novo'
    | '/admin/cadastros/produtos/$id'
    | '/admin/cadastros/produtos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/a-lardan'
    | '/acesso'
    | '/aneis'
    | '/brincos'
    | '/carrinho'
    | '/colares'
    | '/colecoes'
    | '/como-comecar-a-vender-semijoias'
    | '/como-vender-semijoias-pelo-whatsapp'
    | '/contato'
    | '/llms.txt'
    | '/pulseiras'
    | '/renda-extra-com-vendas'
    | '/robots.txt'
    | '/seja-lardan'
    | '/semijoias-consignadas-para-revenda'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/consultora'
    | '/produto/$slug'
    | '/semijoias/$categoria'
    | '/sitemap-products/$pagina'
    | '/semijoias'
    | '/admin/auditoria'
    | '/admin/candidaturas'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/importacao'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/maletas'
    | '/admin/perfil'
    | '/admin/rede'
    | '/admin/site'
    | '/admin/usuarios'
    | '/api/public/ga-config'
    | '/admin'
    | '/admin/cadastros/categorias'
    | '/admin/cadastros/colecoes'
    | '/admin/cadastros/duplicidades'
    | '/admin/cadastros/entidades'
    | '/admin/cadastros/fornecedores'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/pessoas'
    | '/admin/cadastros/produtos'
    | '/admin/candidaturas/$id'
    | '/admin/financeiro/aprovacoes'
    | '/admin/financeiro/auditoria'
    | '/admin/financeiro/centros-custo'
    | '/admin/financeiro/conciliacao'
    | '/admin/financeiro/configuracoes'
    | '/admin/financeiro/contas'
    | '/admin/financeiro/dre'
    | '/admin/financeiro/fluxo-caixa'
    | '/admin/financeiro/importacoes'
    | '/admin/financeiro/pagar'
    | '/admin/financeiro/plano-contas'
    | '/admin/financeiro/receber'
    | '/admin/maletas/$id'
    | '/api/public/midia/$id'
    | '/admin/cadastros'
    | '/admin/financeiro'
    | '/admin/cadastros/pessoas/$id'
    | '/admin/cadastros/pessoas/novo'
    | '/admin/cadastros/produtos/$id'
    | '/admin/cadastros/produtos/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/a-lardan'
    | '/acesso'
    | '/aneis'
    | '/brincos'
    | '/carrinho'
    | '/colares'
    | '/colecoes'
    | '/como-comecar-a-vender-semijoias'
    | '/como-vender-semijoias-pelo-whatsapp'
    | '/contato'
    | '/llms.txt'
    | '/pulseiras'
    | '/renda-extra-com-vendas'
    | '/robots.txt'
    | '/seja-lardan'
    | '/semijoias-consignadas-para-revenda'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/consultora'
    | '/produto/$slug'
    | '/semijoias/$categoria'
    | '/sitemap-products/$pagina'
    | '/semijoias/'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/candidaturas'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/importacao'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/maletas'
    | '/_authenticated/admin/perfil'
    | '/_authenticated/admin/rede'
    | '/_authenticated/admin/site'
    | '/_authenticated/admin/usuarios'
    | '/api/public/ga-config'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cadastros/categorias'
    | '/_authenticated/admin/cadastros/colecoes'
    | '/_authenticated/admin/cadastros/duplicidades'
    | '/_authenticated/admin/cadastros/entidades'
    | '/_authenticated/admin/cadastros/fornecedores'
    | '/_authenticated/admin/cadastros/locais'
    | '/_authenticated/admin/cadastros/pessoas'
    | '/_authenticated/admin/cadastros/produtos'
    | '/_authenticated/admin/candidaturas_/$id'
    | '/_authenticated/admin/financeiro/aprovacoes'
    | '/_authenticated/admin/financeiro/auditoria'
    | '/_authenticated/admin/financeiro/centros-custo'
    | '/_authenticated/admin/financeiro/conciliacao'
    | '/_authenticated/admin/financeiro/configuracoes'
    | '/_authenticated/admin/financeiro/contas'
    | '/_authenticated/admin/financeiro/dre'
    | '/_authenticated/admin/financeiro/fluxo-caixa'
    | '/_authenticated/admin/financeiro/importacoes'
    | '/_authenticated/admin/financeiro/pagar'
    | '/_authenticated/admin/financeiro/plano-contas'
    | '/_authenticated/admin/financeiro/receber'
    | '/_authenticated/admin/maletas_/$id'
    | '/api/public/midia/$id'
    | '/_authenticated/admin/cadastros/'
    | '/_authenticated/admin/financeiro/'
    | '/_authenticated/admin/cadastros/pessoas_/$id'
    | '/_authenticated/admin/cadastros/pessoas_/novo'
    | '/_authenticated/admin/cadastros/produtos_/$id'
    | '/_authenticated/admin/cadastros/produtos_/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  ALardanRoute: typeof ALardanRoute
  AcessoRoute: typeof AcessoRoute
  AneisRoute: typeof AneisRoute
  BrincosRoute: typeof BrincosRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ColaresRoute: typeof ColaresRoute
  ColecoesRoute: typeof ColecoesRoute
  ComoComecarAVenderSemijoiasRoute: typeof ComoComecarAVenderSemijoiasRoute
  ComoVenderSemijoiasPeloWhatsappRoute: typeof ComoVenderSemijoiasPeloWhatsappRoute
  ContatoRoute: typeof ContatoRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PulseirasRoute: typeof PulseirasRoute
  RendaExtraComVendasRoute: typeof RendaExtraComVendasRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SejaLardanRoute: typeof SejaLardanRoute
  SemijoiasConsignadasParaRevendaRoute: typeof SemijoiasConsignadasParaRevendaRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  SemijoiasCategoriaRoute: typeof SemijoiasCategoriaRoute
  SitemapProductsPaginaRoute: typeof SitemapProductsPaginaRoute
  SemijoiasIndexRoute: typeof SemijoiasIndexRoute
  ApiPublicGaConfigRoute: typeof ApiPublicGaConfigRoute
  ApiPublicMidiaIdRoute: typeof ApiPublicMidiaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-lardan': {
      id: '/a-lardan'
      path: '/a-lardan'
      fullPath: '/a-lardan'
      preLoaderRoute: typeof ALardanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aneis': {
      id: '/aneis'
      path: '/aneis'
      fullPath: '/aneis'
      preLoaderRoute: typeof AneisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brincos': {
      id: '/brincos'
      path: '/brincos'
      fullPath: '/brincos'
      preLoaderRoute: typeof BrincosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colares': {
      id: '/colares'
      path: '/colares'
      fullPath: '/colares'
      preLoaderRoute: typeof ColaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes': {
      id: '/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof ColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-comecar-a-vender-semijoias': {
      id: '/como-comecar-a-vender-semijoias'
      path: '/como-comecar-a-vender-semijoias'
      fullPath: '/como-comecar-a-vender-semijoias'
      preLoaderRoute: typeof ComoComecarAVenderSemijoiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-vender-semijoias-pelo-whatsapp': {
      id: '/como-vender-semijoias-pelo-whatsapp'
      path: '/como-vender-semijoias-pelo-whatsapp'
      fullPath: '/como-vender-semijoias-pelo-whatsapp'
      preLoaderRoute: typeof ComoVenderSemijoiasPeloWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulseiras': {
      id: '/pulseiras'
      path: '/pulseiras'
      fullPath: '/pulseiras'
      preLoaderRoute: typeof PulseirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renda-extra-com-vendas': {
      id: '/renda-extra-com-vendas'
      path: '/renda-extra-com-vendas'
      fullPath: '/renda-extra-com-vendas'
      preLoaderRoute: typeof RendaExtraComVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-lardan': {
      id: '/seja-lardan'
      path: '/seja-lardan'
      fullPath: '/seja-lardan'
      preLoaderRoute: typeof SejaLardanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semijoias-consignadas-para-revenda': {
      id: '/semijoias-consignadas-para-revenda'
      path: '/semijoias-consignadas-para-revenda'
      fullPath: '/semijoias-consignadas-para-revenda'
      preLoaderRoute: typeof SemijoiasConsignadasParaRevendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultora': {
      id: '/_authenticated/consultora'
      path: '/consultora'
      fullPath: '/consultora'
      preLoaderRoute: typeof AuthenticatedConsultoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semijoias/': {
      id: '/semijoias/'
      path: '/semijoias'
      fullPath: '/semijoias/'
      preLoaderRoute: typeof SemijoiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semijoias/$categoria': {
      id: '/semijoias/$categoria'
      path: '/semijoias/$categoria'
      fullPath: '/semijoias/$categoria'
      preLoaderRoute: typeof SemijoiasCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-products/$pagina': {
      id: '/sitemap-products/$pagina'
      path: '/sitemap-products/$pagina'
      fullPath: '/sitemap-products/$pagina'
      preLoaderRoute: typeof SitemapProductsPaginaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/candidaturas': {
      id: '/_authenticated/admin/candidaturas'
      path: '/candidaturas'
      fullPath: '/admin/candidaturas'
      preLoaderRoute: typeof AuthenticatedAdminCandidaturasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/importacao': {
      id: '/_authenticated/admin/importacao'
      path: '/importacao'
      fullPath: '/admin/importacao'
      preLoaderRoute: typeof AuthenticatedAdminImportacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/maletas': {
      id: '/_authenticated/admin/maletas'
      path: '/maletas'
      fullPath: '/admin/maletas'
      preLoaderRoute: typeof AuthenticatedAdminMaletasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/perfil': {
      id: '/_authenticated/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AuthenticatedAdminPerfilRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rede': {
      id: '/_authenticated/admin/rede'
      path: '/rede'
      fullPath: '/admin/rede'
      preLoaderRoute: typeof AuthenticatedAdminRedeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/site': {
      id: '/_authenticated/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AuthenticatedAdminSiteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/ga-config': {
      id: '/api/public/ga-config'
      path: '/api/public/ga-config'
      fullPath: '/api/public/ga-config'
      preLoaderRoute: typeof ApiPublicGaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/cadastros/': {
      id: '/_authenticated/admin/cadastros/'
      path: '/cadastros'
      fullPath: '/admin/cadastros/'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/categorias': {
      id: '/_authenticated/admin/cadastros/categorias'
      path: '/cadastros/categorias'
      fullPath: '/admin/cadastros/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/colecoes': {
      id: '/_authenticated/admin/cadastros/colecoes'
      path: '/cadastros/colecoes'
      fullPath: '/admin/cadastros/colecoes'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosColecoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/duplicidades': {
      id: '/_authenticated/admin/cadastros/duplicidades'
      path: '/cadastros/duplicidades'
      fullPath: '/admin/cadastros/duplicidades'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosDuplicidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/entidades': {
      id: '/_authenticated/admin/cadastros/entidades'
      path: '/cadastros/entidades'
      fullPath: '/admin/cadastros/entidades'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosEntidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/fornecedores': {
      id: '/_authenticated/admin/cadastros/fornecedores'
      path: '/cadastros/fornecedores'
      fullPath: '/admin/cadastros/fornecedores'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosFornecedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/locais': {
      id: '/_authenticated/admin/cadastros/locais'
      path: '/cadastros/locais'
      fullPath: '/admin/cadastros/locais'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosLocaisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/pessoas': {
      id: '/_authenticated/admin/cadastros/pessoas'
      path: '/cadastros/pessoas'
      fullPath: '/admin/cadastros/pessoas'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosPessoasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/produtos': {
      id: '/_authenticated/admin/cadastros/produtos'
      path: '/cadastros/produtos'
      fullPath: '/admin/cadastros/produtos'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/candidaturas_/$id': {
      id: '/_authenticated/admin/candidaturas_/$id'
      path: '/candidaturas/$id'
      fullPath: '/admin/candidaturas/$id'
      preLoaderRoute: typeof AuthenticatedAdminCandidaturasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/': {
      id: '/_authenticated/admin/financeiro/'
      path: '/'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/aprovacoes': {
      id: '/_authenticated/admin/financeiro/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/financeiro/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroAprovacoesRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/auditoria': {
      id: '/_authenticated/admin/financeiro/auditoria'
      path: '/auditoria'
      fullPath: '/admin/financeiro/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/centros-custo': {
      id: '/_authenticated/admin/financeiro/centros-custo'
      path: '/centros-custo'
      fullPath: '/admin/financeiro/centros-custo'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroCentrosCustoRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/conciliacao': {
      id: '/_authenticated/admin/financeiro/conciliacao'
      path: '/conciliacao'
      fullPath: '/admin/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/configuracoes': {
      id: '/_authenticated/admin/financeiro/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/financeiro/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/contas': {
      id: '/_authenticated/admin/financeiro/contas'
      path: '/contas'
      fullPath: '/admin/financeiro/contas'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroContasRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/dre': {
      id: '/_authenticated/admin/financeiro/dre'
      path: '/dre'
      fullPath: '/admin/financeiro/dre'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroDreRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/fluxo-caixa': {
      id: '/_authenticated/admin/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/admin/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/importacoes': {
      id: '/_authenticated/admin/financeiro/importacoes'
      path: '/importacoes'
      fullPath: '/admin/financeiro/importacoes'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroImportacoesRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/pagar': {
      id: '/_authenticated/admin/financeiro/pagar'
      path: '/pagar'
      fullPath: '/admin/financeiro/pagar'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroPagarRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/plano-contas': {
      id: '/_authenticated/admin/financeiro/plano-contas'
      path: '/plano-contas'
      fullPath: '/admin/financeiro/plano-contas'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroPlanoContasRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/financeiro/receber': {
      id: '/_authenticated/admin/financeiro/receber'
      path: '/receber'
      fullPath: '/admin/financeiro/receber'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroReceberRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceiroRouteRoute
    }
    '/_authenticated/admin/maletas_/$id': {
      id: '/_authenticated/admin/maletas_/$id'
      path: '/maletas/$id'
      fullPath: '/admin/maletas/$id'
      preLoaderRoute: typeof AuthenticatedAdminMaletasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/midia/$id': {
      id: '/api/public/midia/$id'
      path: '/api/public/midia/$id'
      fullPath: '/api/public/midia/$id'
      preLoaderRoute: typeof ApiPublicMidiaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/cadastros/pessoas_/$id': {
      id: '/_authenticated/admin/cadastros/pessoas_/$id'
      path: '/cadastros/pessoas/$id'
      fullPath: '/admin/cadastros/pessoas/$id'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosPessoasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/pessoas_/novo': {
      id: '/_authenticated/admin/cadastros/pessoas_/novo'
      path: '/cadastros/pessoas/novo'
      fullPath: '/admin/cadastros/pessoas/novo'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosPessoasNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/produtos_/$id': {
      id: '/_authenticated/admin/cadastros/produtos_/$id'
      path: '/cadastros/produtos/$id'
      fullPath: '/admin/cadastros/produtos/$id'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosProdutosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cadastros/produtos_/novo': {
      id: '/_authenticated/admin/cadastros/produtos_/novo'
      path: '/cadastros/produtos/novo'
      fullPath: '/admin/cadastros/produtos/novo'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminFinanceiroRouteRouteChildren {
  AuthenticatedAdminFinanceiroAprovacoesRoute: typeof AuthenticatedAdminFinanceiroAprovacoesRoute
  AuthenticatedAdminFinanceiroAuditoriaRoute: typeof AuthenticatedAdminFinanceiroAuditoriaRoute
  AuthenticatedAdminFinanceiroCentrosCustoRoute: typeof AuthenticatedAdminFinanceiroCentrosCustoRoute
  AuthenticatedAdminFinanceiroConciliacaoRoute: typeof AuthenticatedAdminFinanceiroConciliacaoRoute
  AuthenticatedAdminFinanceiroConfiguracoesRoute: typeof AuthenticatedAdminFinanceiroConfiguracoesRoute
  AuthenticatedAdminFinanceiroContasRoute: typeof AuthenticatedAdminFinanceiroContasRoute
  AuthenticatedAdminFinanceiroDreRoute: typeof AuthenticatedAdminFinanceiroDreRoute
  AuthenticatedAdminFinanceiroFluxoCaixaRoute: typeof AuthenticatedAdminFinanceiroFluxoCaixaRoute
  AuthenticatedAdminFinanceiroImportacoesRoute: typeof AuthenticatedAdminFinanceiroImportacoesRoute
  AuthenticatedAdminFinanceiroPagarRoute: typeof AuthenticatedAdminFinanceiroPagarRoute
  AuthenticatedAdminFinanceiroPlanoContasRoute: typeof AuthenticatedAdminFinanceiroPlanoContasRoute
  AuthenticatedAdminFinanceiroReceberRoute: typeof AuthenticatedAdminFinanceiroReceberRoute
  AuthenticatedAdminFinanceiroIndexRoute: typeof AuthenticatedAdminFinanceiroIndexRoute
}

const AuthenticatedAdminFinanceiroRouteRouteChildren: AuthenticatedAdminFinanceiroRouteRouteChildren =
  {
    AuthenticatedAdminFinanceiroAprovacoesRoute:
      AuthenticatedAdminFinanceiroAprovacoesRoute,
    AuthenticatedAdminFinanceiroAuditoriaRoute:
      AuthenticatedAdminFinanceiroAuditoriaRoute,
    AuthenticatedAdminFinanceiroCentrosCustoRoute:
      AuthenticatedAdminFinanceiroCentrosCustoRoute,
    AuthenticatedAdminFinanceiroConciliacaoRoute:
      AuthenticatedAdminFinanceiroConciliacaoRoute,
    AuthenticatedAdminFinanceiroConfiguracoesRoute:
      AuthenticatedAdminFinanceiroConfiguracoesRoute,
    AuthenticatedAdminFinanceiroContasRoute:
      AuthenticatedAdminFinanceiroContasRoute,
    AuthenticatedAdminFinanceiroDreRoute: AuthenticatedAdminFinanceiroDreRoute,
    AuthenticatedAdminFinanceiroFluxoCaixaRoute:
      AuthenticatedAdminFinanceiroFluxoCaixaRoute,
    AuthenticatedAdminFinanceiroImportacoesRoute:
      AuthenticatedAdminFinanceiroImportacoesRoute,
    AuthenticatedAdminFinanceiroPagarRoute:
      AuthenticatedAdminFinanceiroPagarRoute,
    AuthenticatedAdminFinanceiroPlanoContasRoute:
      AuthenticatedAdminFinanceiroPlanoContasRoute,
    AuthenticatedAdminFinanceiroReceberRoute:
      AuthenticatedAdminFinanceiroReceberRoute,
    AuthenticatedAdminFinanceiroIndexRoute:
      AuthenticatedAdminFinanceiroIndexRoute,
  }

const AuthenticatedAdminFinanceiroRouteRouteWithChildren =
  AuthenticatedAdminFinanceiroRouteRoute._addFileChildren(
    AuthenticatedAdminFinanceiroRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminFinanceiroRouteRoute: typeof AuthenticatedAdminFinanceiroRouteRouteWithChildren
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminCandidaturasRoute: typeof AuthenticatedAdminCandidaturasRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminImportacaoRoute: typeof AuthenticatedAdminImportacaoRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMaletasRoute: typeof AuthenticatedAdminMaletasRoute
  AuthenticatedAdminPerfilRoute: typeof AuthenticatedAdminPerfilRoute
  AuthenticatedAdminRedeRoute: typeof AuthenticatedAdminRedeRoute
  AuthenticatedAdminSiteRoute: typeof AuthenticatedAdminSiteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCadastrosCategoriasRoute: typeof AuthenticatedAdminCadastrosCategoriasRoute
  AuthenticatedAdminCadastrosColecoesRoute: typeof AuthenticatedAdminCadastrosColecoesRoute
  AuthenticatedAdminCadastrosDuplicidadesRoute: typeof AuthenticatedAdminCadastrosDuplicidadesRoute
  AuthenticatedAdminCadastrosEntidadesRoute: typeof AuthenticatedAdminCadastrosEntidadesRoute
  AuthenticatedAdminCadastrosFornecedoresRoute: typeof AuthenticatedAdminCadastrosFornecedoresRoute
  AuthenticatedAdminCadastrosLocaisRoute: typeof AuthenticatedAdminCadastrosLocaisRoute
  AuthenticatedAdminCadastrosPessoasRoute: typeof AuthenticatedAdminCadastrosPessoasRoute
  AuthenticatedAdminCadastrosProdutosRoute: typeof AuthenticatedAdminCadastrosProdutosRoute
  AuthenticatedAdminCandidaturasIdRoute: typeof AuthenticatedAdminCandidaturasIdRoute
  AuthenticatedAdminMaletasIdRoute: typeof AuthenticatedAdminMaletasIdRoute
  AuthenticatedAdminCadastrosIndexRoute: typeof AuthenticatedAdminCadastrosIndexRoute
  AuthenticatedAdminCadastrosPessoasIdRoute: typeof AuthenticatedAdminCadastrosPessoasIdRoute
  AuthenticatedAdminCadastrosPessoasNovoRoute: typeof AuthenticatedAdminCadastrosPessoasNovoRoute
  AuthenticatedAdminCadastrosProdutosIdRoute: typeof AuthenticatedAdminCadastrosProdutosIdRoute
  AuthenticatedAdminCadastrosProdutosNovoRoute: typeof AuthenticatedAdminCadastrosProdutosNovoRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminFinanceiroRouteRoute:
      AuthenticatedAdminFinanceiroRouteRouteWithChildren,
    AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
    AuthenticatedAdminCandidaturasRoute: AuthenticatedAdminCandidaturasRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
    AuthenticatedAdminImportacaoRoute: AuthenticatedAdminImportacaoRoute,
    AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
    AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
    AuthenticatedAdminMaletasRoute: AuthenticatedAdminMaletasRoute,
    AuthenticatedAdminPerfilRoute: AuthenticatedAdminPerfilRoute,
    AuthenticatedAdminRedeRoute: AuthenticatedAdminRedeRoute,
    AuthenticatedAdminSiteRoute: AuthenticatedAdminSiteRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCadastrosCategoriasRoute:
      AuthenticatedAdminCadastrosCategoriasRoute,
    AuthenticatedAdminCadastrosColecoesRoute:
      AuthenticatedAdminCadastrosColecoesRoute,
    AuthenticatedAdminCadastrosDuplicidadesRoute:
      AuthenticatedAdminCadastrosDuplicidadesRoute,
    AuthenticatedAdminCadastrosEntidadesRoute:
      AuthenticatedAdminCadastrosEntidadesRoute,
    AuthenticatedAdminCadastrosFornecedoresRoute:
      AuthenticatedAdminCadastrosFornecedoresRoute,
    AuthenticatedAdminCadastrosLocaisRoute:
      AuthenticatedAdminCadastrosLocaisRoute,
    AuthenticatedAdminCadastrosPessoasRoute:
      AuthenticatedAdminCadastrosPessoasRoute,
    AuthenticatedAdminCadastrosProdutosRoute:
      AuthenticatedAdminCadastrosProdutosRoute,
    AuthenticatedAdminCandidaturasIdRoute:
      AuthenticatedAdminCandidaturasIdRoute,
    AuthenticatedAdminMaletasIdRoute: AuthenticatedAdminMaletasIdRoute,
    AuthenticatedAdminCadastrosIndexRoute:
      AuthenticatedAdminCadastrosIndexRoute,
    AuthenticatedAdminCadastrosPessoasIdRoute:
      AuthenticatedAdminCadastrosPessoasIdRoute,
    AuthenticatedAdminCadastrosPessoasNovoRoute:
      AuthenticatedAdminCadastrosPessoasNovoRoute,
    AuthenticatedAdminCadastrosProdutosIdRoute:
      AuthenticatedAdminCadastrosProdutosIdRoute,
    AuthenticatedAdminCadastrosProdutosNovoRoute:
      AuthenticatedAdminCadastrosProdutosNovoRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedConsultoraRoute: typeof AuthenticatedConsultoraRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedConsultoraRoute: AuthenticatedConsultoraRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  ALardanRoute: ALardanRoute,
  AcessoRoute: AcessoRoute,
  AneisRoute: AneisRoute,
  BrincosRoute: BrincosRoute,
  CarrinhoRoute: CarrinhoRoute,
  ColaresRoute: ColaresRoute,
  ColecoesRoute: ColecoesRoute,
  ComoComecarAVenderSemijoiasRoute: ComoComecarAVenderSemijoiasRoute,
  ComoVenderSemijoiasPeloWhatsappRoute: ComoVenderSemijoiasPeloWhatsappRoute,
  ContatoRoute: ContatoRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PulseirasRoute: PulseirasRoute,
  RendaExtraComVendasRoute: RendaExtraComVendasRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SejaLardanRoute: SejaLardanRoute,
  SemijoiasConsignadasParaRevendaRoute: SemijoiasConsignadasParaRevendaRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  SemijoiasCategoriaRoute: SemijoiasCategoriaRoute,
  SitemapProductsPaginaRoute: SitemapProductsPaginaRoute,
  SemijoiasIndexRoute: SemijoiasIndexRoute,
  ApiPublicGaConfigRoute: ApiPublicGaConfigRoute,
  ApiPublicMidiaIdRoute: ApiPublicMidiaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
