revoke execute on function public.fin_account_detail(uuid) from anon, public;
revoke execute on function public.fin_titles_pending(integer,integer) from anon, public;
revoke execute on function public.fin_chart_list(jsonb) from anon, public;
revoke execute on function public.fin_chart_save(jsonb) from anon, public;
revoke execute on function public.fin_chart_toggle(uuid,boolean) from anon, public;
revoke execute on function public.fin_cost_center_list(jsonb) from anon, public;
revoke execute on function public.fin_cost_center_save(jsonb) from anon, public;
revoke execute on function public.fin_cost_center_toggle(uuid,boolean) from anon, public;
revoke execute on function public.fin_cashflow(jsonb) from anon, public;
revoke execute on function public.fin_audit_list(jsonb) from anon, public;
revoke execute on function public.fin_settings_overview() from anon, public;
revoke execute on function public.fin_payment_method_save(jsonb) from anon, public;
revoke execute on function public.fin_payment_method_toggle(uuid,boolean) from anon, public;
grant execute on function public.fin_account_detail(uuid) to authenticated;
grant execute on function public.fin_titles_pending(integer,integer) to authenticated;
grant execute on function public.fin_chart_list(jsonb) to authenticated;
grant execute on function public.fin_chart_save(jsonb) to authenticated;
grant execute on function public.fin_chart_toggle(uuid,boolean) to authenticated;
grant execute on function public.fin_cost_center_list(jsonb) to authenticated;
grant execute on function public.fin_cost_center_save(jsonb) to authenticated;
grant execute on function public.fin_cost_center_toggle(uuid,boolean) to authenticated;
grant execute on function public.fin_cashflow(jsonb) to authenticated;
grant execute on function public.fin_audit_list(jsonb) to authenticated;
grant execute on function public.fin_settings_overview() to authenticated;
grant execute on function public.fin_payment_method_save(jsonb) to authenticated;
grant execute on function public.fin_payment_method_toggle(uuid,boolean) to authenticated;